import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One sidebar, generated from the docs folders: their numeric prefixes set the order.
const sidebars: SidebarsConfig = {
  handbook: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
