import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One sidebar per tab in the navbar. Each section is a category whose link is the folder's
// index page; the pages inside are generated from the folder (numeric prefixes set the order,
// and the index itself is left out by sidebarItemsGenerator in docusaurus.config.ts).
const section = (label: string, dir: string, collapsed = false) => ({
  type: 'category' as const,
  label,
  collapsed,
  // Doc ids drop the folders' number prefixes; autogenerated items take the folder as it is.
  link: { type: 'doc' as const, id: `${dir.split('/').map((d) => d.replace(/^\d+-/, '')).join('/')}/index` },
  items: [{ type: 'autogenerated' as const, dirName: dir }],
});

const sidebars: SidebarsConfig = {
  overview: [
    { type: 'doc', id: 'start/index', label: 'Start here' },
    section('Glossary', '01-glossary'),
    section('Features end to end', '02-features'),
  ],
  guides: [
    section('Suppliers', '10-supplier'),
    section('Distributors', '11-distributor'),
    section('Resellers and buyers', '12-reseller'),
    section('Platform operator', '20-operator'),
  ],
  api: [
    {
      type: 'category', label: 'Start here', collapsible: false,
      items: ['api/index', 'api/get-access', 'api/quickstart', 'api/user-sessions'],
    },
    {
      type: 'category', label: 'Make requests', collapsible: false,
      items: ['api/authentication', 'api/basics', 'api/requests-and-responses'],
    },
    {
      type: 'category', label: 'Reliability and security', collapsible: false,
      items: ['api/errors', 'api/idempotency', 'api/rate-limits', 'api/live-updates', 'api/security'],
    },
    { ...section('API reference', '30-api/reference'), collapsible: false },
  ],
  reference: [{ type: 'doc', id: 'reference/index', label: 'Reference' }],
};

export default sidebars;
