// An annotated screenshot. The PNG and its callouts are GENERATED by `yarn capture` (capture/):
// the numbered markers are drawn on the page at capture time, and their legend text is written to
// src/data/shots.json beside the image, so the picture and the words cannot disagree.
import useBaseUrl from '@docusaurus/useBaseUrl';
import shots from '@site/src/data/shots.json';

export interface ShotEntry { file: string; width: number; height: number; title?: string; callouts: { n: number; text: string }[] }
const MANIFEST = shots as Record<string, ShotEntry>;

export default function Shot({ id, caption }: { id: string; caption?: string }) {
  const entry = MANIFEST[id];
  const src = useBaseUrl(entry ? `/shots/${entry.file}` : '/');
  if (!entry) return <div className="nh-shot nh-shot--missing">Screenshot <code>{id}</code> appears after the next capture run.</div>;
  return (
    <figure className="nh-shot">
      <div className="nh-shot__frame">
        <img src={src} width={entry.width} height={entry.height} loading="lazy" alt={caption ?? entry.title ?? id} />
      </div>
      {caption && <figcaption className="nh-shot__caption">{caption}</figcaption>}
      {entry.callouts.length > 0 && (
        <ol className="nh-shot__legend">
          {entry.callouts.map((c) => <li key={c.n}><span className="nh-num">{c.n}</span><span>{c.text}</span></li>)}
        </ol>
      )}
    </figure>
  );
}
